"""Write the app's JharkhandMap.kt from jharkhand.json (made by convert.py).

    python3 gen_kotlin.py
"""
import json, math, os
HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.join(HERE, '..', '..', 'android', 'app', 'src', 'main', 'java', 'in', 'sajag', 'geo', 'JharkhandMap.kt')
d = json.load(open(os.path.join(HERE, 'jharkhand.json')))
W, H = d['width'], d['height']
scale = (d['lon1'] - d['lon0']) * math.cos(math.radians((d['lat0'] + d['lat1']) / 2)) / W
lines = []
def enc(ring):
    s = []
    for x, y in ring:
        xi = max(0, min(9999, round(x * 10000))); yi = max(0, min(9999, round(y * 10000)))
        s.append('%04d%04d' % (xi, yi))
    return ''.join(s)
rows = []
for dist in sorted(d['districts'], key=lambda q: q['en']):
    rings = '|'.join(enc(r) for r in dist['rings'])
    lx, ly = dist['label']
    rows.append('        Raw("%s", "%s", "%s", %.4ff, %.4ff,\n            "%s"),' % (dist['id'], dist['en'], dist['hi'], lx, ly, rings))
out = '''package `in`.sajag.geo

import `in`.sajag.i18n.T

/**
 * Jharkhand's 24 districts, simplified for drawing on a phone screen.
 *
 * Boundaries: "India - District Map" (Census 2011 districts) by the DataMeet
 * India community, https://github.com/datameet/maps, shared under Creative
 * Commons Attribution 2.5 India. We simplified the outlines (Douglas-Peucker,
 * about 2 px on a 1000 px wide map) and projected them equirectangular at the
 * state's middle latitude. Good for a risk picture; not for surveying.
 *
 * Coordinates are normalised so the map is [WIDTH] wide and [HEIGHT] tall,
 * with y growing downwards like the screen. Each point is stored as two
 * four-digit numbers (x and y times 10 000); rings are separated by "|".
 *
 * Generated by tools/jharkhand-map/gen_kotlin.py. Do not edit by hand.
 */
class District(
    val id: String,
    val name: T,
    val rings: List<FloatArray>,
    val labelX: Float,
    val labelY: Float,
)

object Jharkhand {
    const val WIDTH = %.4ff
    const val HEIGHT = %.4ff

    // The projection, so a GPS position can be put on the map.
    private const val LON_WEST = %.6f
    private const val LAT_NORTH = %.6f
    private const val COS_MID_LAT = %.6f
    private const val DEGREES_PER_UNIT = %.6f

    /** Map coordinates of a longitude and latitude (WGS 84). */
    fun project(lon: Double, lat: Double): Pair<Float, Float> = Pair(
        ((lon - LON_WEST) * COS_MID_LAT / DEGREES_PER_UNIT).toFloat(),
        ((LAT_NORTH - lat) / DEGREES_PER_UNIT).toFloat(),
    )

    val districts: List<District> by lazy { RAW.map(::parse) }

    fun byId(id: String?): District? = districts.firstOrNull { it.id == id }

    /** The district under a point in map coordinates, or null for outside the state. */
    fun districtAt(x: Float, y: Float): District? =
        districts.firstOrNull { d -> d.rings.any { contains(it, x, y) } }

    /** Even-odd ray casting. [ring] is x0, y0, x1, y1, ... */
    fun contains(ring: FloatArray, x: Float, y: Float): Boolean {
        var inside = false
        val n = ring.size / 2
        var j = n - 1
        for (i in 0 until n) {
            val xi = ring[2 * i]
            val yi = ring[2 * i + 1]
            val xj = ring[2 * j]
            val yj = ring[2 * j + 1]
            if ((yi > y) != (yj > y) && x < (xj - xi) * (y - yi) / (yj - yi) + xi) inside = !inside
            j = i
        }
        return inside
    }

    private class Raw(val id: String, val en: String, val hi: String, val lx: Float, val ly: Float, val data: String)

    private fun parse(raw: Raw): District {
        val rings = raw.data.split('|').map { s ->
            FloatArray(s.length / 4) { i -> s.substring(i * 4, i * 4 + 4).toInt() / 10_000f }
        }
        return District(raw.id, T(raw.en, raw.hi), rings, raw.lx, raw.ly)
    }

    private val RAW = listOf(
%s
    )
}
''' % (W, H, d['lon0'], d['lat1'], math.cos(math.radians((d['lat0'] + d['lat1']) / 2)), scale, '\n'.join(rows))
open(TARGET, 'w', encoding='utf-8').write(out)
print(len(out), 'bytes', W, H)
